# Merge to main
#
name: Parent Job

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: read
  id-token: write
  actions: write

jobs:

  Invoke-Teams-Workflow:
    name: Invoke Teams Workflow
    uses: sas-institute-rnd-ci360/eks-runner/.github/workflows/Teams-Notification.yml@main
    with:
      parent-job: Invoke Teams Workflow
    secrets: inherit



  Follow-up-Job:
    runs-on: ubuntu-latest
    name: Follow up Job
    needs:
      - Invoke-Teams-Workflow
    steps:
      - name: send notification
        uses: dchourasia/ms-teams-notification@1.1
        with:
           webhook-uri: https://sasoffice365.webhook.office.com/webhookb2/916137af-ddd2-414a-89a3-fc4ea8b76957@b1c14d5c-3625-45b3-a430-9552373a0c2f/JenkinsCI/917aefeb984a43b09c57dd35904076dc/191827ef-9406-42df-bc45-18ef3083908f
           github-token: ${{ github.token }}
           card-layout-exit: complete
           job-name: Follow up Job

      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          mkdir logs
          cd logs
          echo test, and deploy your project > artifact_1.txt
          echo Add other actions to build > artifact_2.txt

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: archive logs
          path: |
            logs